#+OPTIONS: toc:nil H:10 tex:t
#+OPTIONS: author:nil date:nil
#+LATEX_HEADER: \renewcommand\maketitle{}
#+STARTUP: hidestars indent
#+INCLUDE: personal-info.org
#+LaTeX_HEADER: \usepackage{mycv}
#+LaTeX_HEADER: \hypersetup{colorlinks=true, urlcolor={url-gray}}
#+LaTeX_CLASS_OPTIONS: [letterpaper]
#+LaTeX_HEADER: \usepackage{enumitem}
#+LaTeX_HEADER: \setlist{leftmargin=0.25in,nosep}
#+LaTeX_HEADER: \usepackage{multicol}

{{{HEADER}}}

* Professional Knowledge
** Programming languages
Ruby (3 years, 20k SLOC), Perl (5 years, 20k SLOC), C (4 years, 20k SLOC), Golang (1 year, 2k SLOC), Java (1 year, 2k SLOC), JavaScript (3 years, 10k SLOC), HTML+CSS (8 years), some knowledge of Assembler, PHP, Emacs Lisp, Lua, Elixir, Erlang, Zurb Foundation, Bootstrap
** Build and CI/CD Tools
Jenkins (4 years), Artifactory (4 years), Travis-CI(2 years), Maven(4 years), Gradle(2 years), little experience with Ant+Ivy, GNU Make
** Web Servers, Application web servers
Nginx(7 years), Openresty (1 year), php-fpm(7 years), Tomcat (2 years), Apache(1 year), some experience with writing own webservers using libmicrohttpd, libwebsockets
** Automation Tools, Provisioners
Chef (3 years), Ansible (1 year), Docker (1 year), some experience in Puppet (2 months), CFEngine (long-long ago)
** Metrics, Monitoring Systems
ELK (3 years), syslog (3 years), Jmeter, Tsung, Nagios, Zabbix, New Relic, Pingdom(automated steps via CSS selectors)
** Databases
MySQL (6 years), Redis (2 years), Solr (2 years), MongoDB(2 years), Elasticsearch. Some experience with PostgreSQL and SQLite3
** Datacenters, Clouds, Hypervisors
AWS (worked with EC2, EBS, ELB, CloudWatch, CloudFormation, CloudFront, Route53, used separate VPC per environment, ECS), VMWare, VirtualBox, Vagrant. Some knowledge of KVM, QEMU, libvirt
** Tools
Emacs(6 years), Vim(1 year), Bash(7 years), POSIX shell environment and utilities, Linux (12 years, mostly RedHat family, Gentoo and server administration), FreeBSD (4 years), Git (4 years), SVN (1 year), expect

* Experience
** Technical Operations Engineer at [[https://quickblox.com][QuickBlox]]
*** Jul 2016 - Mar 2017
Proposed to stop using ~provided~ in dependency scopes to prevent manual dependency upload to the container\\
Introduced ELK\\
Proposed a new approach in determining expected timings for login into chat using normalization to the speed of light\\
Performed load tests using Tsung, Jmeter, own load test scripts. Found bottleneck in Jmeter\\
By indirect evidences made an assumption the Customer experiences problems because they intercept and substitute SSL certificates. Made a laboratory stand and checked with developers. Later, the Customer confirmed they did not put their self-signed CA to their device\\
** DevOps Engineer at [[https://epam.com][EPAM]]
*** Nov 2014 - Jul 2016
Worked a lot with maintaining Adobe CQ (AEM) farm:
- Developed and implemented deployment scheme using ~Jenkins~, ~curl~
- Developed, implemented backing the data up, restoration of the data, content migration
- Proposed to resolve coordinates by Apache instead of writing tons of Java code
- Wrote procedure for migration behind CDN, made all needed preparations
- Acted as a medium between the team and company network center
Developed a CloudFormation scenario with persisting the data on EBS\\
L2 support engineer for [[http://autotrader.co.za][autotrader.co.za]]
- Moved from using separate Apaches to Nginx installed along with each Tomcat. This optimization gave us 6 free instances in AWS
- Developed a logic for automatic artifacts deploy to Job servers based on the release installed on main servers
- Implemented blacklisting in Nginx based on headers (e.g. User-Agent, Referer, etc) and source IP
- Introduced Cicada cycles in job scheduling so jobs did not interfere each another
Completed internal course for Java Spring CLI applications (where I used AOP) and a course for Spring MVC, SOAP\\
Lecturer on internal preproduction courses for students
** Technical Operations Engineers at [[http://toa-ukraine.com][TOA-Ukraine (Now Oracle)]]
*** May 2010 - Nov 2014
Developed a WEB interface for managing CFEngine configuration.\\
Developed a WEB interface where QA engineer can build test environment in several clicks\\
Worked on improving Demo instances:
- Switched from per-VM installations (40) to multitenant instances running in the same VM - 200 instances using the same hardware, i.e. decreased the cost per instance in 5 times
- Developed a Self-Care scenario where sales representative books Demo instance in several clicks without writing any e-mails or involving someone to provide the instance. Gathered requirements, act as product owner, worked in cooperation with Development team 
Introduced new approaches in delivering the code to servers, checking human mistakes, problem investigation\\
Wrote a lot of useful scripts such as
- Mantis informer - ~Gtk2~ tray icon popups if there are changes in ticket queue and assigns the ticket to me if new tickets match some configurable criteria (we played a game in team, the winner is the man who solved most problems/tickets)
- Load test script for stress tesing our Login Portal. The script used asynchronous events approach, so we were able to generate enough requests even from small machines. The result was better than we expected: we found a bottleneck and our DNS was also affected during the test
- Script opens several tabs in terminal and spawns multiple ssh connection. Used ~expect~
** System Administrator at [[https://www.ksd.ua/en/][Family Leisure Club]]
*** Sep 2009 - May 2010
Maintained two phone stations OfficeServ 500 and OfficeServ 7400 in two locations\\
Minimized expences regarding phone calls
- Configured calls between two offices to go through ethernet instead of paid PRI channels
- Introduced low cost providers
- Switched from manual dialing external trunk group to Low Cost Routing (LCR using tables 710, 712 and 714) by first entered numbers
- Introduced phone calls from distant shops over IP
- Wrote perl script for log aggregation from phone station and comparing the numbers with the bill
** Linux Administrator, Field Engineer, Service Desk Engineer at various ISPs
*** Mar 2005 - Jul 2009
Developed Home Entrance Video Monitoring Sytem running on first channel in cable TV.
Introduced planning and terms prediction to be better in chaffering for a new project. Administered campus network. Increased income by changing billing strategy from per computer to per personal account.
Worked as 1st and 2nd line support engineer

* Projects

** Wife's shop
[[https://bars.kh.ua][Women's bags]] is a personal project where I help my wife to sell handbags and other leather stuff. She adds an item and it is automatically published in social networks. Reversed a part of Instagram API related to uploading images
** [[https://github.com/AlexJakeGreen/bars][Web application skel]]
This is a set of initial files I use as a start point for writing web site in Golang
** cpu8080, cpu8086
[[https://github.com/AlexJakeGreen/cpu8080][cpu8080]] and [[https://github.com/AlexJakeGreen/cpu8086][cpu8086]] are my practice in writing cpu emulators, improving Assembler knowledge and understanding of how computers work after all.
* Education
** Kharkiv National University of Radio Electronics
*** Aug 2003 - Jun 2008
Telecommunication Technologies, Faculty of Electronic Devices
*** Sep 2007 - May 2009
Economical Cybernetics, Faculty of Applied Mathematics and Management
